list=[]
student_name_1= str(input("Enter the Name of First Student: "))
student_marks_1=int(input("Enter the Marks of First Student:"))
student_name_2= str(input("Enter the Name of Second Student:"))
student_marks_2=int(input("Enter the Marks of Second Student: "))
student_name_3= str(input("Enter the Name of Third Student: "))
student_marks_3=int(input("Enter the Marks of Third Student: "))
student_name_4= str(input("Enter the Name of Fourth Student: "))
student_marks_4=int(input("Enter the Marks of Fourth Student: "))
student_name_5= str(input("Enter the Name of Fifth Student: "))
student_marks_5=int(input("Enter the Marks of Fifth Student: "))
list.append(student_name_1)
list.append(student_marks_1)
list.append(student_name_2)
list.append(student_marks_2)
list.append(student_name_3)
list.append(student_marks_3)
list.append(student_name_4)
list.append(student_marks_4)
list.append(student_name_5)
list.append(student_marks_5)
print("The Lists of marks of five students with names are as follows: " ,list)
